# Generated by Django 5.0.1 on 2024-01-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Details',
        ),
    ]
