# Generated by Django 5.0.1 on 2024-01-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_travel_emsn', models.IntegerField(null=True)),
                ('gl_energy_emsn', models.IntegerField(null=True)),
                ('gl_food_emsn', models.IntegerField(null=True)),
                ('gl_water_emsn', models.IntegerField(null=True)),
                ('gl_waste_emsn', models.IntegerField(null=True)),
                ('gl_appliance_emsn', models.IntegerField(null=True)),
                ('gl_daily_emsn', models.IntegerField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='User_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_emsn', models.IntegerField()),
                ('travel_emsn', models.IntegerField()),
                ('energy_emission', models.IntegerField()),
                ('water_emission', models.IntegerField()),
                ('waste_emission', models.IntegerField()),
                ('appliance_emission', models.IntegerField()),
                ('daily_emsn', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_details')),
            ],
        ),
    ]
